name: Artifacts Upload

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  start-runner:
    name: Start self-hosted EC2 runner
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_RUNNER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_RUNNER_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_RUNNER_REGION }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.AWS_RUNNERS_ACCESS_TOKEN }}
          ec2-image-id: ${{ secrets.AWS_RUNNER_PYTHON_EC2_IMAGE_ID }}
          ec2-instance-type: ${{ secrets.AWS_RUNNER_EC2_INSTANCE_TYPE }}
          subnet-id: ${{ secrets.AWS_RUNNER_SUBNET_ID }}
          security-group-id: ${{ secrets.AWS_RUNNER_SECURITY_GROUP_ID }}
          iam-role-name: ${{ secrets.AWS_RUNNER_IAM_ROLE_NAME }}
          aws-resource-tags: >
            [
              {"Key": "Name", "Value": "github-python-runner"},
              {"Key": "GitHubRepository", "Value": "${{ github.repository }}"}
            ]
